# Generated by Django 4.2.19 on 2025-04-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
